### ISSUE TITLE
FEEDBACK

### ISSUE THREAD

**Issue by marixxa** [Tomasvii/mercadoLiebre#1]
Excelente trabajo, todos los puntos se cumplen, hasta los que no estaban pedidos como el del mensaje de error en los formularios.
Todo muy prolijo.
Como único comentario a tener en cuenta solo por una cuestión visual, seria centrar los input del login a la misma altura de los botones.

**Comment by Tomasvii** [comment]
Perfecto Marisa, gracias!

Recordá que el issue debes cerrarlo vos.
